dist: trusty
sudo: required

notifications:
  email:
    - yunthanatos@gmail.com

language: go

go:
  - 1.8.3

compiler:
  - gcc

install:
    - sudo apt-get install -qq -y libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make build-essential
    
script:
    - export GOROOT_BOOTSTRAP=$GOROOT
    - echo $GOROOT_BOOTSTRAP $GOROOT
    - cd src
    - ./make.bash
    - echo ":)"
    - cd ../bin
    - ldd go
    - echo strace -s 100 -f ./go tool trace -h
    - date
